### ISSUE TITLE
Error in for loops since last commit #83197c8d6271ab62a594b56024e4e1fb50be0505

### ISSUE THREAD

**Issue by MikyGonzalez** [colinhect/nominal#20]
For the given code:

```
fib := [ n |
  if: (n < 2) [
    n
  ] [
    fib: (n - 1) + fib: (n - 2)
  ]
]

expected := { 0, 1, 2, 3, 5, 8, 13, 21 }

forKeys: expected [ n |
  assertEqual: (fib: n) expected[n]
]

completed := true
```

We get on console and test suite: `Error: No variable 'n' in scope`.

Reserving `n := 0` before for loop N not iterate it. And always stay like 0. 
Also getting Segmentation Fault when high values (stack values in recursion), for Fib > 26.

**Comment by colinhect** [comment]
Yeah, the last commit broke more than I intended.  I'll likely revert it and rethink how modes are going to work.

**Comment by colinhect** [comment]
Commit #83197c8d6271ab62a594b56024e4e1fb50be0505 has been reverted
